# Generated by Django 4.2.3 on 2023-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_bid_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.IntegerField(default=5),
        ),
    ]
